# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0cserver.proto\"E\n\x0b\x43\x61llRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\r\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x12\n\nparameters\x18\x03 \x01(\x0c\"4\n\x0c\x43\x61llResponse\x12\x13\n\x0bresponse_id\x18\x01 \x01(\r\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"\x06\n\x04Void\" \n\x0b\x43hannelInfo\x12\x11\n\ton_server\x18\x01 \x01(\x08\x32\xca\x01\n\rServerService\x12*\n\x0b\x63\x61ll_method\x12\x0c.CallRequest\x1a\r.CallResponse\x12%\n\rsend_response\x12\r.CallResponse\x1a\x05.Void\x12\x1f\n\x0fsend_heart_beat\x12\x05.Void\x1a\x05.Void\x12 \n\x10reply_heart_beat\x12\x05.Void\x1a\x05.Void\x12#\n\x0cinit_channel\x12\x0c.ChannelInfo\x1a\x05.VoidB\x03\x90\x01\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CALLREQUEST = _descriptor.Descriptor(
  name='CallRequest',
  full_name='CallRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='CallRequest.request_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='method', full_name='CallRequest.method', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='CallRequest.parameters', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=85,
)


_CALLRESPONSE = _descriptor.Descriptor(
  name='CallResponse',
  full_name='CallResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_id', full_name='CallResponse.response_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='CallResponse.content', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=139,
)


_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=147,
)


_CHANNELINFO = _descriptor.Descriptor(
  name='ChannelInfo',
  full_name='ChannelInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='on_server', full_name='ChannelInfo.on_server', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=181,
)

DESCRIPTOR.message_types_by_name['CallRequest'] = _CALLREQUEST
DESCRIPTOR.message_types_by_name['CallResponse'] = _CALLRESPONSE
DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['ChannelInfo'] = _CHANNELINFO

CallRequest = _reflection.GeneratedProtocolMessageType('CallRequest', (_message.Message,), dict(
  DESCRIPTOR = _CALLREQUEST,
  __module__ = 'server_pb2'
  # @@protoc_insertion_point(class_scope:CallRequest)
  ))
_sym_db.RegisterMessage(CallRequest)

CallResponse = _reflection.GeneratedProtocolMessageType('CallResponse', (_message.Message,), dict(
  DESCRIPTOR = _CALLRESPONSE,
  __module__ = 'server_pb2'
  # @@protoc_insertion_point(class_scope:CallResponse)
  ))
_sym_db.RegisterMessage(CallResponse)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), dict(
  DESCRIPTOR = _VOID,
  __module__ = 'server_pb2'
  # @@protoc_insertion_point(class_scope:Void)
  ))
_sym_db.RegisterMessage(Void)

ChannelInfo = _reflection.GeneratedProtocolMessageType('ChannelInfo', (_message.Message,), dict(
  DESCRIPTOR = _CHANNELINFO,
  __module__ = 'server_pb2'
  # @@protoc_insertion_point(class_scope:ChannelInfo)
  ))
_sym_db.RegisterMessage(ChannelInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\220\001\001'))

_SERVERSERVICE = _descriptor.ServiceDescriptor(
  name='ServerService',
  full_name='ServerService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=184,
  serialized_end=386,
  methods=[
  _descriptor.MethodDescriptor(
    name='call_method',
    full_name='ServerService.call_method',
    index=0,
    containing_service=None,
    input_type=_CALLREQUEST,
    output_type=_CALLRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='send_response',
    full_name='ServerService.send_response',
    index=1,
    containing_service=None,
    input_type=_CALLRESPONSE,
    output_type=_VOID,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='send_heart_beat',
    full_name='ServerService.send_heart_beat',
    index=2,
    containing_service=None,
    input_type=_VOID,
    output_type=_VOID,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='reply_heart_beat',
    full_name='ServerService.reply_heart_beat',
    index=3,
    containing_service=None,
    input_type=_VOID,
    output_type=_VOID,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='init_channel',
    full_name='ServerService.init_channel',
    index=4,
    containing_service=None,
    input_type=_CHANNELINFO,
    output_type=_VOID,
    options=None,
  ),
])

ServerService = service_reflection.GeneratedServiceType('ServerService', (_service.Service,), dict(
  DESCRIPTOR = _SERVERSERVICE,
  __module__ = 'server_pb2'
  ))

ServerService_Stub = service_reflection.GeneratedServiceStubType('ServerService_Stub', (ServerService,), dict(
  DESCRIPTOR = _SERVERSERVICE,
  __module__ = 'server_pb2'
  ))


# @@protoc_insertion_point(module_scope)
